### ISSUE TITLE
pytest is intalled for nose stack

### ISSUE THREAD

**Issue by dmakhno** [allure-framework/allure-nose-adaptor#2]
```
pip show nose-allure-plugin pytest-allure-adaptor lxml pytest namedlist six enum34
---
Name: nose-allure-plugin
Version: 1.0
Location: /Library/Python/2.7/site-packages
Requires: nose, pytest-allure-adaptor
---
Name: pytest-allure-adaptor
Version: 1.5.4
Location: /Library/Python/2.7/site-packages
Requires: lxml, **pytest**, namedlist, six, enum34
```

**Comment by sergeychipiga** [comment]
Hi @dmakhno,
Yea, it's right, because nose-allure-plugin uses modules, implemented inside pytest-allure-adaptor.

**Comment by dmakhno** [comment]
@sergeychipiga,
I understand that, but frankly saying, install `pytest`, for `nosetests` tools is not "fair".

**Comment by sergeychipiga** [comment]
@dmakhno yep, absolutely agree. It would be a great to separate ```allure-python-adaptor``` and ```pytest-allure-plugin``` in order to use independently. But it's not so quick. Any case, thanks for your opinion.
